import type { Metadata } from "next";
import { Share, Share_Tech } from "next/font/google";
import "./globals.css";
import "remixicon/fonts/remixicon.css";
import "leaflet/dist/leaflet.css";

const shareTech = Share_Tech({
  variable: "--font-share-tech",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${shareTech.className} ${shareTech.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
